# Notebook 02: Huis Data Exploratie

In [2]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path.cwd().parent / "locatie_data"

In [3]:
df_huis = pd.read_parquet(
    DATA_DIR / "huis788.parquet"
)

In [4]:
df_huis.head()

,timestamp,CO2,CTYPE,ENAME,ENE,EONNAME,ETYPE,GNAME,POW,CO2_IMP,...,CO2_EXP,COST,COST_EXP,ENE_CNT_EXP,ENE_EXP,CO2EQ,ESTYPE,forecast.ENE,forecast.POW,PRICE
0,2024-03-08 01:00:00+01:00,NaN,electricity,boiler-16eda211b788,NaN,eiot-16eda211b788,boiler,SERENE,6.504839,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-03-08 01:05:00+01:00,0.099741,electricity,boiler-16eda211b788,0.542070,eiot-16eda211b788,boiler,SERENE,6.490000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-03-08 01:10:00+01:00,0.099513,electricity,boiler-16eda211b788,0.540833,eiot-16eda211b788,boiler,SERENE,6.461972,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-03-08 01:15:00+01:00,0.099084,electricity,boiler-16eda211b788,0.538498,eiot-16eda211b788,boiler,SERENE,6.477778,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-03-08 01:20:00+01:00,0.099326,electricity,boiler-16eda211b788,0.539815,eiot-16eda211b788,boiler,SERENE,6.461039,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_huis.info()

<class 'pandas.DataFrame'>
RangeIndex: 3057890 entries, 0 to 3057889
Data columns (total 24 columns):
 #   Column        Dtype
---  ------        -----
 0   timestamp     datetime64[us, Europe/Amsterdam]
 1   CO2           float64
 2   CTYPE         str
 3   ENAME         str
 4   ENE           float64
 5   EONNAME       str
 6   ETYPE         str
 7   GNAME         str
 8   POW           float64
 9   CO2_IMP       float64
 10  COST_IMP      float64
 11  CTYPEC        str
 12  ENE_CNT_IMP   float64
 13  ENE_IMP       float64
 14  CO2_EXP       float64
 15  COST          float64
 16  COST_EXP      float64
 17  ENE_CNT_EXP   float64
 18  ENE_EXP       float64
 19  CO2EQ         float64
 20  ESTYPE        str
 21  forecast.ENE  float64
 22  forecast.POW  float64
 23  PRICE         float64
dtypes: datetime64[us, Europe/Amsterdam](1), float64(16), str(7)
memory usage: 716.3 MB

In [6]:
df_huis.describe().T

,count,mean,std,min,25%,50%,75%,max
CO2,940640.0,4.753729e+00,9.093405e+02,-5.180328e+03,0.000000,4.760000e-01,2.844000e+00,6.066280e+05
ENE,1422314.0,6.184638e+05,7.607598e+07,-6.432414e+06,0.000000,2.000000e+00,1.000000e+01,9.358267e+09
POW,1121431.0,2.119905e+02,7.537093e+02,-3.456934e+03,5.000000,5.742056e+01,4.039604e+02,7.255976e+03
CO2_IMP,707954.0,6.631111e+00,1.048100e+03,0.000000e+00,0.000000,2.550000e-01,3.006000e+00,6.066280e+05
COST_IMP,1122989.0,2.004792e+02,2.182276e+04,0.000000e+00,0.000000,2.540840e-04,2.794924e-03,2.385336e+06
ENE_CNT_IMP,1123353.0,1.385691e+09,3.324023e+09,-1.393403e+06,416187.000000,1.291044e+06,2.559994e+07,9.389882e+09
ENE_IMP,1141386.0,7.763103e+05,8.519306e+07,0.000000e+00,0.000000,1.000000e+00,1.100000e+01,9.387983e+09
CO2_EXP,691716.0,1.954165e+00,1.012028e+01,-4.480111e+01,0.000000,0.000000e+00,0.000000e+00,5.180328e+03
COST,1133980.0,1.970967e+02,2.164793e+04,-1.634373e+03,0.000000,2.540840e-04,2.286756e-03,2.377786e+06
COST_EXP,1124254.0,1.451793e+00,1.026791e+02,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,8.150980e+03
ENE_CNT_EXP,1124617.0,8.836919e+06,1.299611e+07,0.000000e+00,0.000000,9.000000e+00,2.888108e+07,3.218408e+07
ENE_EXP,1126580.0,5.701995e+03,4.036976e+05,-1.163333e+02,0.000000,0.000000e+00,0.000000e+00,3.207986e+07
CO2EQ,168068.0,2.737777e+02,1.374936e+02,2.300000e+01,146.000000,2.660000e+02,3.950000e+02,5.740000e+02
forecast.ENE,17300.0,7.665000e-01,1.487191e+01,-1.665679e+02,0.000000,7.253576e-04,5.127931e-01,1.240100e+02
forecast.POW,17300.0,9.198000e+00,1.784630e+02,-1.998815e+03,0.000000,8.704291e-03,6.153518e+00,1.488120e+03
PRICE,267763.0,1.882318e-01,9.237225e-02,-6.804009e-02,0.087719,2.540840e-01,2.540840e-01,2.748714e-01