# Notebook 03: Middenhuis Data Exploratie

In [2]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path.cwd().parent / "locatie_data"

In [3]:
df_middenhuis = pd.read_parquet(
    DATA_DIR / "middenhuis479.parquet"
)

In [4]:
df_middenhuis.head()

,timestamp,CO2EQ,CTYPE,ENAME,EONNAME,ETYPE,GNAME,CO2,ENE,POW,...,COST_IMP,CTYPEC,ENE_CNT_EXP,ENE_CNT_IMP,ENE_EXP,ENE_IMP,ESTYPE,forecast.ENE,forecast.POW,PRICE
0,2024-03-08 01:05:00+01:00,184.0,electricity,co2ele_92be2eca45,eiot-5335bae8d497,co2equivalent,SERENE,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-03-08 01:10:00+01:00,184.0,electricity,co2ele_92be2eca45,eiot-5335bae8d497,co2equivalent,SERENE,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-03-08 01:15:00+01:00,184.0,electricity,co2ele_92be2eca45,eiot-5335bae8d497,co2equivalent,SERENE,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-03-08 01:20:00+01:00,184.0,electricity,co2ele_92be2eca45,eiot-5335bae8d497,co2equivalent,SERENE,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-03-08 01:25:00+01:00,184.0,electricity,co2ele_92be2eca45,eiot-5335bae8d497,co2equivalent,SERENE,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_middenhuis.info()

<class 'pandas.DataFrame'>
RangeIndex: 3493093 entries, 0 to 3493092
Data columns (total 24 columns):
 #   Column        Dtype
---  ------        -----
 0   timestamp     datetime64[us, Europe/Amsterdam]
 1   CO2EQ         float64
 2   CTYPE         str
 3   ENAME         str
 4   EONNAME       str
 5   ETYPE         str
 6   GNAME         str
 7   CO2           float64
 8   ENE           float64
 9   POW           float64
 10  CO2_EXP       float64
 11  CO2_IMP       float64
 12  COST          float64
 13  COST_EXP      float64
 14  COST_IMP      float64
 15  CTYPEC        str
 16  ENE_CNT_EXP   float64
 17  ENE_CNT_IMP   float64
 18  ENE_EXP       float64
 19  ENE_IMP       float64
 20  ESTYPE        str
 21  forecast.ENE  float64
 22  forecast.POW  float64
 23  PRICE         float64
dtypes: datetime64[us, Europe/Amsterdam](1), float64(16), str(7)
memory usage: 821.5 MB

In [6]:
df_middenhuis.describe().T

,count,mean,std,min,25%,50%,75%,max
CO2EQ,166360.0,2.715002e+02,1.373385e+02,2.300000e+01,144.000000,2.630000e+02,3.930000e+02,5.740000e+02
CO2,1082141.0,-8.844159e-01,3.878712e+03,-2.809292e+06,0.000000,0.000000e+00,5.252523e+00,6.112781e+05
ENE,1637196.0,-1.153034e+02,1.981524e+05,-1.994015e+07,0.000000,0.000000e+00,2.500000e+01,1.370824e+07
POW,1029752.0,1.330210e+02,1.219671e+03,-5.671690e+03,0.000000,1.272288e+02,5.701899e+02,9.938500e+03
CO2_EXP,858429.0,1.261552e+01,4.234536e+03,-9.385105e+01,0.000000,0.000000e+00,0.000000e+00,2.809292e+06
CO2_IMP,874940.0,1.000387e+01,1.214805e+03,0.000000e+00,0.000000,0.000000e+00,5.709000e+00,6.319501e+05
COST,1368878.0,-3.582746e-02,5.506105e+01,-5.066474e+03,0.000000,0.000000e+00,4.827596e-03,3.483045e+03
COST_EXP,1360456.0,1.053088e+00,7.464155e+01,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,5.991063e+03
COST_IMP,1362501.0,1.015506e+00,5.696962e+01,0.000000e+00,0.000000,0.000000e+00,6.606184e-03,4.747011e+03
ENE_CNT_EXP,1360933.0,6.957810e+06,9.789219e+06,0.000000e+00,184.000000,1.720400e+04,1.639531e+07,2.818786e+07
ENE_CNT_IMP,1362976.0,6.121791e+06,6.626107e+06,-1.295886e+07,731962.000000,2.779022e+06,1.114389e+07,2.086541e+07
ENE_EXP,1361556.0,4.141258e+03,2.936486e+05,-2.376350e+02,0.000000,0.000000e+00,0.000000e+00,2.357906e+07
ENE_IMP,1378320.0,3.951753e+03,2.229257e+05,0.000000e+00,0.000000,0.000000e+00,2.700000e+01,1.868284e+07
forecast.ENE,17294.0,-9.932403e-02,2.106058e+01,-3.602400e+02,0.000000,0.000000e+00,6.787211e-01,2.453984e+02
forecast.POW,17294.0,-1.191888e+00,2.527269e+02,-4.322880e+03,0.000000,0.000000e+00,8.144654e+00,2.944781e+03
PRICE,267763.0,1.882131e-01,9.239748e-02,-6.804009e-02,0.087726,2.540840e-01,2.540840e-01,2.748714e-01