# Notebook 04: Carport Data Exploratie

In [2]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path.cwd().parent / "locatie_data"

In [3]:
df_carport = pd.read_parquet(
    DATA_DIR / "carport.parquet"
)

In [4]:
df_carport.head()

,timestamp,CO2EQ,CTYPE,ENAME,EONNAME,ETYPE,GNAME,CTYPEC,ESTYPE,forecast.ENE,...,CO2_EXP,CO2_IMP,ENE_EXP,ENE_IMP,COST,COST_EXP,COST_IMP,ENE_CNT_EXP,ENE_CNT_IMP,PRICE
0,2024-04-19 02:05:00+02:00,138.0,electricity,co2ele_92be2eca45,eiot-e4393cd3dfdb,co2equivalent,SERENE,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-04-19 02:10:00+02:00,138.0,electricity,co2ele_92be2eca45,eiot-e4393cd3dfdb,co2equivalent,SERENE,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-04-19 02:15:00+02:00,138.0,electricity,co2ele_92be2eca45,eiot-e4393cd3dfdb,co2equivalent,SERENE,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-04-19 02:20:00+02:00,138.0,electricity,co2ele_92be2eca45,eiot-e4393cd3dfdb,co2equivalent,SERENE,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-04-19 02:25:00+02:00,138.0,electricity,co2ele_92be2eca45,eiot-e4393cd3dfdb,co2equivalent,SERENE,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_carport.info()

<class 'pandas.DataFrame'>
RangeIndex: 4888431 entries, 0 to 4888430
Data columns (total 24 columns):
 #   Column        Dtype
---  ------        -----
 0   timestamp     datetime64[us, Europe/Amsterdam]
 1   CO2EQ         float64
 2   CTYPE         str
 3   ENAME         str
 4   EONNAME       str
 5   ETYPE         str
 6   GNAME         str
 7   CTYPEC        str
 8   ESTYPE        str
 9   forecast.ENE  float64
 10  forecast.POW  float64
 11  ENE           float64
 12  POW           float64
 13  CO2           float64
 14  CO2_EXP       float64
 15  CO2_IMP       float64
 16  ENE_EXP       float64
 17  ENE_IMP       float64
 18  COST          float64
 19  COST_EXP      float64
 20  COST_IMP      float64
 21  ENE_CNT_EXP   float64
 22  ENE_CNT_IMP   float64
 23  PRICE         float64
dtypes: datetime64[us, Europe/Amsterdam](1), float64(16), str(7)
memory usage: 1.1 GB

In [6]:
df_carport.describe().T

,count,mean,std,min,25%,50%,75%,max
CO2EQ,158933.0,2.673036e+02,1.369833e+02,2.300000e+01,1.420000e+02,2.520000e+02,3.880000e+02,5.920000e+02
forecast.ENE,17294.0,-3.489334e+01,2.029266e+02,-3.420935e+03,0.000000e+00,0.000000e+00,1.389563e+00,8.809117e+02
forecast.POW,17294.0,-4.187201e+02,2.435119e+03,-4.105122e+04,0.000000e+00,0.000000e+00,1.667476e+01,1.057094e+04
ENE,2521771.0,3.173046e+08,5.197092e+10,-4.048535e+08,0.000000e+00,0.000000e+00,2.000000e+00,8.512504e+12
POW,2227169.0,2.358808e+13,1.355048e+18,-1.403426e+21,-2.250000e+01,0.000000e+00,2.308108e+02,1.455960e+21
CO2,1484058.0,-1.051674e+01,4.514530e+04,-3.005066e+07,0.000000e+00,0.000000e+00,2.064000e+00,2.982812e+07
CO2_EXP,716387.0,2.426773e+02,6.546618e+04,-1.060649e+03,0.000000e+00,0.000000e+00,3.142400e+01,3.005066e+07
CO2_IMP,942325.0,1.510735e+02,6.845941e+04,0.000000e+00,0.000000e+00,0.000000e+00,2.327273e+00,5.987814e+07
ENE_EXP,1377032.0,5.217569e+15,6.281503e+17,-2.758833e+03,0.000000e+00,0.000000e+00,1.600000e+01,7.562905e+19
ENE_IMP,1847221.0,3.889497e+15,5.423505e+17,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,7.562906e+19
COST,1812606.0,1.121646e+05,1.557528e+07,-1.028668e+05,0.000000e+00,0.000000e+00,0.000000e+00,2.162891e+09
COST_EXP,1326445.0,1.376259e+12,1.626177e+14,0.000000e+00,0.000000e+00,0.000000e+00,5.081680e-03,1.921613e+16
COST_IMP,1767294.0,1.032954e+12,1.408841e+14,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.921613e+16
ENE_CNT_EXP,1373199.0,3.182734e+18,1.518478e+19,-5.383785e+06,4.333200e+05,5.711991e+07,1.351093e+08,7.562905e+19
ENE_CNT_IMP,1837359.0,1.949589e+18,1.198519e+19,1.100000e+01,4.307324e+06,7.117354e+06,4.720287e+07,7.562906e+19
PRICE,244180.0,1.818719e-01,9.432611e-02,-6.804009e-02,8.229086e-02,2.540840e-01,2.540840e-01,2.748714e-01